name:                leaderboard
version:             0.1.0
github:              "dsomni/haskell-flappy-bird"
license:             BSD3

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dsomni/haskell-flappy-bird>

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >=1.0.2 && <1.1

ghc-options:
- -Wall -fno-warn-type-defaults

dependencies:
- base >= 4.7 && < 5
- text
- random
- scotty
- aeson
- wai
- HDBC
- HDBC-postgresql >= 2.5.0.1


default-extensions:
- OverloadedStrings
- ImportQualifiedPost
- RecordWildCards

library:
  source-dirs: src

executables:
  leaderboard:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - leaderboard
  
tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-flappy-bird
    - hspec
    build-tools:
    - hspec-discover:hspec-discover

  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
    - base
    - doctest
    - Glob
    - QuickCheck
    - template-haskell
