version: "3"
services:
  haskell-flappy-bird-client:
    image: sl1depengwyn/haskell-flappy-bird-client:latest
    ports:
      - "80:80"
    environment:
      LEADER_BOARD_HOST: "http://leaderboard:8080"

  leaderboard:
    image: sl1depengwyn/haskell-flappy-bird-leaderboard:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_CONNECTION_STRING: "host=db port=5432 user=user password=password dbname=flappybird"

    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flappybird

volumes:
  db-data:
