name: Client Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - "game/**"
  pull_request:
    branches:
      - main
    paths:
      - "game/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./game
          file: ./game/Dockerfile
          push: true
          tags: sl1depengwyn/haskell-flappy-bird-client:latest
